### ISSUE TITLE
plot to sanity check predictions

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#102]
In one row, show rgz, norris, Fan et. al. and our own predictions.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/16574909/24556bd8-42c7-11e6-87a5-8275abc64aaa.png)

Here's a couple of different ways the image could be scaled. I want a method that doesn't pack too many values down to the same value, and spreads out the distribution a lot. Constant stretching and logarithms look like good ideas.

**Comment by chengsoonong** [comment]
How about log(x+1) where x is the pixel value? You want to avoid log(0), but at the same time there are a lot of black pixels, which you want to remain black.

**Comment by MatthewJA** [comment]
+1 gives almost the same results as just using the original image. It's still a very sharp peak and hard to make out features.

**Comment by chengsoonong** [comment]
Ok then. Constant stretching looks good from your plots.

**Comment by MatthewJA** [comment]
I agree. My worry is that it bunches up a little at the top &mdash; so lots of bright areas have the same value.

For actually displaying, constant stretching is good, but I'm curious as to whether it would work as a pre-CNN filter.

**Comment by chengsoonong** [comment]
The saturation at the top (255) and bottom (0) probably need some other procedure. Steve Gould recommended doing a Gaussian smoothing over the image to reduce the saturation at the top. At this point, I don't think it is worth it. I suggest that you get your code working (with good instructions), and then I'll try to convince one of his PhD students to optimise your CNN pipeline.

**Comment by MatthewJA** [comment]
Sounds good. I think that even with the saturation it's probably better than the original, so I'll implement the stretching (pretty easy to do), train a CNN, and see how it goes.

**Comment by ivyw** [comment]
Have you tried clipping + a sqrt or an asinh stretch?   These are the common stretches used by astronomers too.

**Comment by MatthewJA** [comment]
I hadn't. Just tried sqrt which looks quite good. Not sure how to do an asinh stretch so I'll investigate that.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/16606520/f6b2e812-437b-11e6-9ca3-2772f312567d.png)

Here's the probabilities output by the classifier (circles), with larger/pinker circles representing higher probabilities. Green stars represent Norris et al. labels.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/16641737/e13e6cb0-4446-11e6-8845-4b11cc128149.png)

**Comment by MatthewJA** [comment]
3ef72b2caa50f5127d67df2d065644f90271fec5
