### ISSUE TITLE
increase committee diversity

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#103]
- reduce the number of training examples for each member of committee
- check that each member of committee is better than random

**Comment by chengsoonong** [comment]
- Have half logistic regression and half random forest

**Comment by MatthewJA** [comment]
As expected, adding random forests increases committee diversity, with 545 radio subjects with >=50% disagreement.

**Comment by MatthewJA** [comment]
Also, switching from WISE to SWIRE increases diversity. I suspect it raises the number of ambiguous hosts.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/16675744/22c095da-4507-11e6-9712-432a17b8f33e.png)

50% subset with 5 RF and 5 LR classifiers. Horizontal axis is percentage agreement.

**Comment by chengsoonong** [comment]
This looks like too much diversity, as there is _NO_ agreement. WISE seems to be a newer survey, so perhaps use WISE. Increasing the number of training examples might be good.

**Comment by MatthewJA** [comment]
WISE should reduce diversity so I'll load that up and give it a try. Past that I can also fiddle with some parameters and see if we can get a good distribution out.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/16685143/6170cdc8-454c-11e6-87d2-8bcffa0b726d.png)

90% subsets, committee of 2 RFs and 8 LRs.
