### ISSUE TITLE
understand committee disagreement

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#104]
Use Gaussian mixture models to cluster the predictions of the committee.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/16674689/2fe2d0ce-44fe-11e6-9ddc-c6f0d5448e73.png)

Need to fix up the visualising a bit, but looks like a disagreeing committee behaves like the crowd!

**Comment by chengsoonong** [comment]
It is good that your committee behaves like the crowd.
