### ISSUE TITLE
Write up experimental design and performance against Norris et al. label set

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#105]
Carried from #92.

**Comment by MatthewJA** [comment]
Preliminaries for this in 14b20fc12776f6eade94685147b5700d5ce49a4a.

**Comment by MatthewJA** [comment]
I've written a bunch of pipeline stuff into the thesis document. Going to roll on through into the experimental stuff.

**Comment by MatthewJA** [comment]
Currently working on some writing on this topic (I need a break from staring at Python).

**Comment by MatthewJA** [comment]
> Present the distribution of confidences (of all data points) as a violin plot.

@chengsoonong: Can I get a clarification on [this](https://github.com/chengsoonong/crowdastro/issues/92#issuecomment-227713315)? I'm not entirely sure what you meant.

**Comment by MatthewJA** [comment]
To do:
- Make ROC/precision-recall curves
- Make confusion matrix
- Document performance against the majority vote labels
- Repeat all of this for the radio-based experiments

**Comment by chengsoonong** [comment]
Regarding presenting performances as violin plots. You have 10 repeats (random splits of training/testing). Each split gives you a test error. The standard way (which you follow) is to report the mean and standard error or these 10 numbers.  Instead, plot the violin plot (or box and whisker plot) of these 10 numbers. This tells you about outliers, skewness, etc.

**Comment by MatthewJA** [comment]
Alright, sounds good.

#99 is probably relevant (CNN peeking).
