### ISSUE TITLE
Write up click consensus

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#106]
From #16.

**Comment by ivyw** [comment]
Hi @MatthewJA,
I've been trying to characterise "randomness" in the DR1 FIRST consensus distributions and came to the conclusion that I need more information about the users and their clicking habits. For example, are there individual users who appear to click 10 times more host identifications per subject than other users of the same subjects. 

Upon speaking to Julie, she mentioned that you are doing something more sophisticated on the click consensus within the ATLAS data so I would be very interested in reading your write-up on this work.  Can you point me to this write-up? 

Thanks in advance,
Ivy

**Comment by MatthewJA** [comment]
Hi Ivy.

I haven't yet written the write-up (am working on it now!) but I will link you to that when I've finished it. In the interim, here is a very quick summary of my method.

For finding click consensuses I'm clustering the volunteers' clicks using a Gaussian mixture model. The number of Gaussians is found by minimising the Bayesian information criterion over a grid search. This effectively partitions the volunteers' clicks into subsets; the mean of each subset can be taken to find the consensus for that partition. The consensus for the whole subject is the consensus of the partition with the most elements.

This doesn't account for choosing multiple host locations for the same radio combination. As far as I'm aware this is a limitation of both my approach and the KDE approach (though please correct me if I'm wrong!). I'm not sure how to handle that situation yet.

**Comment by MatthewJA** [comment]
I'm reasonably happy with the writeup in fc886ef. It's about a page. I'm not sure if it needs to be more detailed.

**Comment by MatthewJA** [comment]
@ivyw: The write-up is [here](https://github.com/chengsoonong/crowdastro/blob/master/tex/thesis/thesis.tex#L117) (starting line 132) in my thesis. Please let me know if you need more information!

**Comment by ivyw** [comment]
Hi @MatthewJA, This is great. Thanks heaps for your quick response.  I'll digest it more thoroughly before getting back to you on this.
cheers,
ivy
