### ISSUE TITLE
Start bib file, add all read papers

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#107]
For thesis.tex, there should be a corresponding bib file, that should be used with latex and bibtex. Add all the papers that have been read to the bib file, along with a list of bullet points in the main document, with one bullet for each paper.

**Comment by MatthewJA** [comment]
I've got a bib file [here](https://github.com/chengsoonong/crowdastro/blob/master/tex/papers.bib) of all papers I used in COMP4450, though I haven't got a list of bullet points. I'll add that soon for a subset of the papers in the bib.

**Comment by MatthewJA** [comment]
I only added papers that I've read really thoroughly, or are particularly relevant. When I read more, I'll add them, too.

The bib file on the other hand is (to my best recollection) exhaustive and contains every paper I've looked at.
