### ISSUE TITLE
Field map and table

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#108]

**Comment by MatthewJA** [comment]
Surprisingly hard to find the field locations...

Roughly,
- ELAIS-S1 (ATLAS, SWIRE, WISE) is centred on 00 38 30 -44 00 00 and covers an area of ~14 deg²,
- CDFS (ATLAS, SWIRE, WISE) is centred on 03 32 00 -28 16 00 and covers an area of ~7 deg²,
- FIRST is a radio survey that roughly covers a rectangle from 18 65 to 07 -10 and a rectangle from 04 15 to -10 21 (this mostly overlaps with SDSS, I believe), and
- WISE is an all-sky infrared survey.

ATLAS is a radio survey and SWIRE is an infrared survey.

I still need to find the resolutions.

**Comment by ivyw** [comment]
Julie might know for ATLAS but the resolution of SWiRE is ~1.8 arcseconds.

**Comment by jbanfield** [comment]
FIRST is roughly 5 arcsec

ATLAS - CDFS is 16 x 7 arcsec
ATLAS - ELAIS SI is 12 x 8 arcsec

**Comment by MatthewJA** [comment]
Thanks!

I'm going to resolve this &mdash; a visual map is probably not useful since the sizes of the surveys are so different.
