### ISSUE TITLE
Unify documentation

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#11]
The first file people read is README.md. The other files should either be merged or referred to. Try to keep the README brief (1-2 pages). The user should know what to do next after reading README.

**Comment by MatthewJA** [comment]
Perhaps we should only use in-repo documentation, then, rather than the wiki? It's about as easy to edit if you've got push access, and everything would still be markdown.

**Comment by chengsoonong** [comment]
Some project management stuff might be more suitable outside the repo, but in general, everything should be in the repo.

**Comment by MatthewJA** [comment]
Sure. I'll move all the wiki stuff into a docs/ directory in the repo and reference it from the README.

**Comment by chengsoonong** [comment]
My current favourite for documentation is:
http://www.mkdocs.org/
