### ISSUE TITLE
Put Yan (2011), Mozafari (2012), and Dasgupta (2011) into the same notation

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#110]

**Comment by chengsoonong** [comment]
Very minor, so not a new issue:

Database file #1: ../papers.bib
Warning--no number and no volume in banfield16
Warning--page numbers missing in banfield16
Warning--page numbers missing in mozafari12
Warning--no number and no volume in yan11

**Comment by MatthewJA** [comment]
An update on this &mdash; I've spent a while seeing if I can figure out a label complexity for Yan 2011. I'm pretty sure that once you discard label noise and multiple annotators, you basically recover uncertainty sampling since all you have left is that the point you should sample is argmin_x (0.5 - p(z | x))² (the labeller to sample is trivial). I'll see if I can follow the derivation of the label complexity for the Cohn et al. paper and apply it to uncertainty sampling. One problem is that uncertainty sampling is pool-based and Cohn et al. isn't, and I'm still not sure how to deal with that (or if it's even possible).
