### ISSUE TITLE
Express QBC in terms of noisy GBS

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#111]
This is an alternative to issue #110.

Query by Committee:
Freund, Seung, Shamir, Tishby, Selective Sampling Using the Query by Committee Algorithm, 1997
Noisy Generalised Binary Search:
http://papers.nips.cc/paper/3721-noisy-generalized-binary-search.pdf
https://arxiv.org/pdf/0910.4397.pdf

**Comment by MatthewJA** [comment]
I'll have a thorough read of these papers and decide which to do based on that.
