### ISSUE TITLE
dataset on zenodo

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#113]

**Comment by MatthewJA** [comment]
What license do you think is appropriate for the dataset? ATLAS [seems to be public domain](http://www.atnf.csiro.au/research/deep/data_release/index.htm) and WISE seems to only require that we say "This publication makes use of data products from the Wide-field Infrared Survey Explorer, which is a joint project of the University of California, Los Angeles, and the Jet Propulsion Laboratory/California Institute of Technology, funded by the National Aeronautics and Space Administration." somewhere. I think some kind of Creative Commons is a good idea but you probably have a better idea than me. If you don't have an opinion either way I'll figure out which CC license to use.

**Comment by chengsoonong** [comment]
Start at CC0, and figure out whether that's suitable. Other than that, I don't have an opinion.

**Comment by MatthewJA** [comment]
Okay. What should I put as your affiliation? Data61, NICTA, ANU? Your last paper has all three but I'm not sure which one to use here.

**Comment by chengsoonong** [comment]
My Affiliations are "ANU" and "Data61, CSIRO".

**Comment by MatthewJA** [comment]
Thanks.

CC website suggests [Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) so I'll use that.

**Comment by MatthewJA** [comment]
Final question—to what extent should the Radio Galaxy Zoo data + authors be mentioned in the Zenodo upload? As far as I'm aware the RGZ classifications are not licensed and I haven't been able to find anything to the contrary. Options range from including people as authors, including people as contributors, mentioning the Radio Galaxy Zoo _à la_ WISE, or none of the above.

(I'm a little out of my depth here.)

Ping @jbanfield—is the RGZ data licensed and/or do you have a preference for how I should reference the RGZ data?

**Comment by jbanfield** [comment]
The following should be mentioned/referenced.

**RGZ** 
Reference Banfield et al. (2015) "Radio Galaxy Zoo: host galaxies and radio morphologies derived from visual inspection" Monthly Notices of the Royal Astronomical Society, Volumne 453, Issue 3, p.2326-2340.

The Radio Galaxy Zoo data has been made possible by the participation of more then 10,000 volunteers in the Radio Galaxy Zoo project.  Their contributions are individually acknowledged at http://rgzauthors.galaxyzoo.org.  

**ATLAS**
Reference Franzen et al. (2015) "ATLAS - I. Third release of 1.4GHz mosaics and component catalogues" Monthly Notices of the Royal Astronomical Society, Volume 453, Issue 4, p.4020-4036.

Australia Telescope Compact Array is part of the Australia Telescope, which is funded by the Commonwealth of Australia for operation as a National Facility managed by CSIRO.

**SWIRE**
This work is based on archival data obtained with the Spitzer Space Telescope, which is operated by the Jet Propulsion Laboratory, California Institute of Technology under a contract with NASA.

**Comment by MatthewJA** [comment]
Thanks!

**Comment by MatthewJA** [comment]
[Done!](https://zenodo.org/record/58316)

**Comment by chengsoonong** [comment]
Nice. Please document in our repo. :-)

**Comment by MatthewJA** [comment]
Updated readme in a7adee89c396b0a67e876b26eaa497da5f9444dd. We have a DOI badge! :D
