### ISSUE TITLE
Setup webhooks for Read the Docs

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#117]
I can't setup webhooks for RtD as I don't have admin access to this repo. Could you please setup webhooks? Instructions [here](http://read-the-docs.readthedocs.io/en/latest/webhooks.html#github).

**Comment by chengsoonong** [comment]
Webhooks set up. Not clear what should be the trigger.

**Comment by MatthewJA** [comment]
I think it's a push trigger. I'll push something and see!

**Comment by MatthewJA** [comment]
Yup, it's push. All good!
