### ISSUE TITLE
How many good labellers are there?

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#119]
- proportion of crowd where variance is small
- proportion of experts where variance is small
- proportion of crowd where mean is good
- proportion of experts where mean is good

**Comment by MatthewJA** [comment]
Blocked on #120 for anonymous users; I'll investigate for non-anonymous users if possible.

**Comment by MatthewJA** [comment]
Apparently only 15% of the ATLAS classifications are from anonymous users! That's much lower than I'd expected.

**Comment by MatthewJA** [comment]
Blocked on getting Yan working properly.

**Comment by MatthewJA** [comment]
#178
