### ISSUE TITLE
Cross-identifying anonymous labellers

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#120]
For the Yan algorithms I need to be able to identify which labels were made by the same people. I have usernames for registered users but need a way to identify anonymous users.

Every label has an IP address. I don't have that IP address (nor do I want that IP address) since my data are anonymised, but I would like to get an anonymised version if possible. I think one way to do this would be to salt and hash the IP addresses, e.g. `md5(ip_address + secret_str)`.

I talked to @jbanfield about this briefly on the walk back to the uni.

**Comment by jbanfield** [comment]
do you still want me to check if this is possible?

**Comment by MatthewJA** [comment]
Yes, that would be good &mdash; maybe it will turn out that there are more anonymous volunteers for FIRST, or that the anonymous volunteers are interesting in some way. If it's a lot of effort though then don't worry about it for now and I'll make do with the non-anonymous volunteers (which seem to be the majority).

**Comment by jbanfield** [comment]
Email sent but I have a feeling Ed (our developer) has left.  Added Micheal to email.

**Comment by MatthewJA** [comment]
Just to keep this issue updated, Michael has said that they are already using something very similar to the hashing I suggested, so with the exception of a technical issue across a number of annotations, we should be able to cross-identify most of the anonymous annotations.

**Comment by MatthewJA** [comment]
Got a copy of the anonymous-labelled data!
