### ISSUE TITLE
Identify regions where Yan et al. (2010) fails to converge

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#122]

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/17285117/0402d792-5804-11e6-8712-c8984672e3f9.png)

Also curious if this is a local minimum. Hm.

**Comment by chengsoonong** [comment]
You might want to try using an odd number of annotators, just in case you have tie breaking issues.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/17314044/86db6288-58a4-11e6-8f08-075a77739d82.png)

No dice.

Edit 1: Unless it's discounting annotator 1 entirely. I'll try with annotator 1 having decent labels.

Edit 2: That didn't work either. Ah well.

**Comment by MatthewJA** [comment]
One additional note is that LBFGS seems to require accurately scaled gradients &mdash; the gradients in my implementation might be out by a factor of `T` as this isn't given explicitly in the paper.

**Comment by chengsoonong** [comment]
Good observation. Making sure that you are taking the gradient of the **average** and not the **total** over the size of the crowd would be very important. This is why I ask you to write down your full derivation in LaTeX, so that we can check such things.

**Comment by MatthewJA** [comment]
My gradient comes out as a total since the optimisation target is a total (for α and β at any rate). Then again, my newly-derived gradient equations are also different from the paper, so I need to try and find where my mistake is. Wolfram|Alpha agrees with me so the problem must be earlier on somehow...

Pushed most of it in 84d42e8, just missing the last two gradients.

**Comment by chengsoonong** [comment]
I just read the experimental section of Yan 2010. In the experiments for Part I, they simulated annotators by clustering the data. Each annotator is an expert on one cluster (returns ground truth label), and returns a noisy label for all other clusters. It would be weird if your label noise needs to behave like that for EM to work, but this seems to be worth implementing anyway, because it allows you to reproduce a prior experiment for demonstrating that this model works.

This is to rule out that your method for generating annotators is somehow violating some assumption (I cannot see what this could be).

**Comment by MatthewJA** [comment]
Sounds good to me. I'll do that soon.

**Comment by MatthewJA** [comment]
A little bit of algebra-bashing today has lead me to think that this probably should be converging &mdash; though I don't think I know enough information theory to prove it. I also consistently get different gradients to the paper, so I'll try implementing my gradients and see how it goes.

**Comment by MatthewJA** [comment]
I've gone ahead and implemented my gradients and I get identical behaviour (despite the gradients being different?). This is really strange.

**Comment by MatthewJA** [comment]
(Sorry for the inundation of email notifications!)

Here's a plot of the different values of the optimisation objective for different values of α_1 and α_2 and other parameters 0.
![image](https://cloud.githubusercontent.com/assets/2681312/17360935/46bb056a-59b1-11e6-933f-7f1a7a9e9128.png)

The other variables are pretty similar. Given this, I'm pretty confused as to how the values could diverge. I suspect the gradients are wrong, though I can't see where implementation differs from the paper.

Fixing γ = 1, w = 0 for all annotators (I believe this is equivalent to trusting that they have low noise), only searching for α and β, approximating the gradient, and initialising α and β normally at random consistently gives good results.

![image](https://cloud.githubusercontent.com/assets/2681312/17361898/17f0d7aa-59b6-11e6-8bef-15fb11d95702.png)

Again fixing γ and w and searching only for α and β, but using the analytic gradients, gives mixed results. Usually similar to the above, but sometimes everything is classified as the same class.

The same experiment with my own gradients for α and β also gives similarly mixed results.

The same experiment but unfixing γ (initialising to 1) slightly decreases quality of results; γ seems to go up (implying an increase in confidence &mdash; even for labellers who are totally wrong). I can't seem to get it to drop the value of γ below the initial value.

The same experiment but using my own gradient for γ does pretty well! It manages to discount the labels from people who are always wrong, outputting γ:

`γ = [ 0.1615422   1.88785567  1.84692105  1.08089441]`

Annotator 1 always labels class 0, and annotator 4 is wrong 30% of the time. Annotator 2 is slightly better than annotator 3.

I also note that it's possible for the system to get stuck into a loop where it convinces itself that all the labels _should_ be zero, and then proceeds to discount everyone who isn't annotator 1:

`γ = [ 17.1624761    0.08013397   1.04591933  -0.57535758]`

All this considered, I decided to plot the gradients of γ for different values of γ with random values for all other parameters and values. I get these curves, with Yan gradients in blue and my gradients in green:

![image](https://cloud.githubusercontent.com/assets/2681312/17363283/cbc84eba-59bc-11e6-8b17-0eb7db369d53.png)

Mine are larger by a factor of 100(!) so I've scaled them back a bit. The interesting thing is that (conditionally &mdash; not sure what causes this) the Yan gradients are always positive or always negative, while mine are -sgn(γ) (at least for the random data). Noting that the scale was also off, I divided my gradients by 100 and ran the test again. This gave pretty good results. I'm not sure why the scale was so different.

![image](https://cloud.githubusercontent.com/assets/2681312/17363372/5bfeb05a-59bd-11e6-8d47-908bba952b46.png)

`γ = [ 0.2266155   4.92412781  0.67983324  0.59036428]`

I then went all in with my gradients and optimised over all parameters. This quite consistently gives good results (or decides that annotator 1 is always right).

**Comment by chengsoonong** [comment]
Perhaps you are testing with something that is too hard. Annotator 1 seems to be always predicting one class only (which is hard for a learner who expects balanced class proportions).

I suggest something easy, where all annotators agree on most of the examples (90-95%) and only a few examples have one annotator getting it wrong. If that's fiddly to implement, just have a very very low noise level.

**Comment by MatthewJA** [comment]
Good idea. Switching annotator 1 to behave like annotator 3 over a different domain gives good results.

**Comment by MatthewJA** [comment]
This is still with the initial assumption that the annotators are not bad &mdash; that seems to be the main factor that has improved the results. I think this is because if you start out with normally distributed (or zero) γ, you start out assuming that half of the annotators should be ignored and this can easily bias your labels when there aren't many annotators. To try this out, I'll boost the number of annotators and see if it improves stability. (edit: It does.)

I'm reminded a little of optimism in reinforcement learning, where you start out assuming that all rewards are quite good.

**Comment by MatthewJA** [comment]
> Each annotator is an expert on one cluster (returns ground truth label), and returns a noisy label for all other clusters. It would be weird if your label noise needs to behave like that for EM to work, but this seems to be worth implementing anyway, because it allows you to reproduce a prior experiment for demonstrating that this model works.

Working on this now.

**Comment by MatthewJA** [comment]
Simplified the data a bit by increasing separation and making everything linearly separable. Good results usually:

![image](https://cloud.githubusercontent.com/assets/2681312/17393841/7a39b478-5a69-11e6-8bf0-5e6a34b75f39.png)

Sometimes the results are bad though:
![image](https://cloud.githubusercontent.com/assets/2681312/17393898/b519e7fc-5a69-11e6-9c20-71d03225564b.png)

I also added a small constant to η_t &mdash; Yan et al. did this for σ_t but there's no mention of adding a small constant for η_t. This seems to have improved stability a lot. I'm pretty happy with this now though I do I wish it were more reliable.

**Comment by MatthewJA** [comment]
> Each annotator is an expert on one cluster (returns ground truth label), and returns a noisy label for all other clusters. It would be weird if your label noise needs to behave like that for EM to work, but this seems to be worth implementing anyway, because it allows you to reproduce a prior experiment for demonstrating that this model works.

Forgot to follow up on this. Implemented + tested, no obvious differences.
