### ISSUE TITLE
Prediction results tables

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#125]
3 tables (CSV files) for ATLAS
1. **predictions**: IAU name, rgz, pred. consensus, pred. raw, Norris, Fan
2. **RGZ**: IAU name, galaxy, subject, num components, num peaks
3. **astro**: IAU name, characteristics ... e.g. location

**Comment by chengsoonong** [comment]
Item 1 above is issue #121.
Item 2 and 3 should be able to be output by @jbanfield [script](https://github.com/chengsoonong/crowdastro/blob/master/crowdastro/rgzatlascat.py)

**Comment by chengsoonong** [comment]
For @MatthewJA education:
http://www.bkent.net/Doc/simple5.htm
Relational databases and normal forms.

**Comment by MatthewJA** [comment]
@jbanfield: Should this table be made using WISE or using SWIRE? Norris and Fan both use SWIRE.

**Comment by jbanfield** [comment]
First thing will be to match with SWIRE.  Then go to WISE.  You just have to include the SWIRE name as that would be the look up for the SWIRE table.  Same for WISE.

**Comment by jbanfield** [comment]
Yes the script can output these columns.  Adding to my todo.

**Comment by MatthewJA** [comment]
Okay, so match to SWIRE rather than WISE. In that case, do you think I should report on SWIRE in my thesis? Or just WISE (given WISE will be used for EMU)? Or both?

**Comment by MatthewJA** [comment]
I guess I'll do both!

**Comment by jbanfield** [comment]
I think it would be a good to do both.  (1) matching to SWIRE provides comparison to what has already been done; (2) matching to WISE determines what the completeness with WISE will be going forward with EMU.  How many WISE matches are not the same as the SWIRE results?

**Comment by MatthewJA** [comment]
Sounds good to me!

> How many WISE matches are not the same as the SWIRE results?

What do you mean by this?

**Comment by jbanfield** [comment]
The resolution of WISE is poor.  In some cases there will be more than one SWIRE source per WISE source. The location of the IR source will not be able to determine the SWIRE counterpart but could find the WISE counterpart.  I recall that this occurs around 5% of the time but I would like to quantify that number.

**Comment by MatthewJA** [comment]
Hmm, okay. I'll have to have a think about how to find that number. Intuitively, if there's a crowd click that's within 3'' of one WISE object but multiple SWIRE objects, then that's a case where the WISE match is not the same as a SWIRE match?

**Comment by chengsoonong** [comment]
Cite (in preparation) paper, Banfield et. al.

**Comment by MatthewJA** [comment]
Cited (as Alger et al. as per Julie's email).

**Comment by MatthewJA** [comment]
Ping #144 for reference.
