### ISSUE TITLE
Think about how to store model, predictions

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#128]

**Comment by MatthewJA** [comment]
#155

**Comment by MatthewJA** [comment]
I can convert the model to an array and put it in the same HDF5 file.

**Comment by chengsoonong** [comment]
Don't forget to store version numbers and functions to interpret your array that represents a model. E.g. logistic regression in sklearn.

**Comment by MatthewJA** [comment]
Ah, good point. Will fix.

**Comment by MatthewJA** [comment]
Resolved in 85dfd1c!
