### ISSUE TITLE
Run code on the RSAA server

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#129]
(unrelated to #116)

**Comment by MatthewJA** [comment]
Blocked on the server not having python3. @jbanfield, are there any updates on whether the server has Python 3 yet?

**Comment by jbanfield** [comment]
Not currently.  Will check tomorrow with sysadmin

**Comment by MatthewJA** [comment]
Any luck?

Incidentally, I tried out the code in Python 2 just to see what would happen &mdash; looks like a strange issue in Python 2's `astropy` that doesn't happen in Python 3's `astropy`. I can't fix it as far as I can tell.

**Comment by MatthewJA** [comment]
Just checked the server &mdash; Python 3 still isn't installed. Might be worth bumping the issue?

**Comment by jbanfield** [comment]
I chatted with them on Friday.  They will install python 3.5

**Comment by MatthewJA** [comment]
Thanks Julie. (It still isn't installed as of right now, but I'll close this issue once it is.)

**Comment by jbanfield** [comment]
Python 3.5 installed

**Comment by MatthewJA** [comment]
I can't seem to find it. Is this on misfit?

edit: Just read your note in the other issue. All good
