### ISSUE TITLE
Compare analytic gradients to approximate gradients, sampling h

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#130]

**Comment by MatthewJA** [comment]
Implemented gradients and approximate gradient are _totally and completely different_ by _huge_ amounts. Woo!

**Comment by MatthewJA** [comment]
Implemented my gradients. Distance from the true gradient to the implemented gradient for those specified in the paper is ~900, from the true gradient to my gradient implemented is ~10. Less wrong, but still wrong! Shall investigate further.

**Comment by MatthewJA** [comment]
β gradient is (probably) correct. The difference between the gradients is less than 0.03, e.g.

> `(0.45118195400229488, 0.43674759085903875, 0.014434363143256135)`

of the form `(approx gradient, my gradient, difference)`.

**Comment by chengsoonong** [comment]
When comparing numbers of indeterminate scale, it is useful to compare the difference as a ratio of one of the numbers.

E.g. 0.014/0.45

**Comment by MatthewJA** [comment]
Ah, okay, shall do in future!

**Comment by MatthewJA** [comment]
β gradient was very slightly off; numbers are now the same for all intents and purposes. α gradient is also correct. Currently working on w, γ.

**Comment by chengsoonong** [comment]
Write a unit test please.
