### ISSUE TITLE
submodule, subtree, subrepo

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#139]
@MatthewJA What do you think of bleeding edge?
https://github.com/ingydotnet/git-subrepo

**Comment by MatthewJA** [comment]
Bleeding edge is fun!

Questionable Windows compatibility though. I'd have to test it.

**Comment by MatthewJA** [comment]
I don't really mind which of these we pick, but if we pick something, we can close this issue. So whatever works for you.

**Comment by chengsoonong** [comment]
Added as submodule in commit 652777d42da96d0db0ef4d4d15a835469b5b3dc1

https://github.com/chengsoonong/crowdastro-projects
