### ISSUE TITLE
Make 5 test sets with 50% random samples of Fan ∩ Norris

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#146]

**Comment by chengsoonong** [comment]
Since we are doing random sampling (without replacement), I suggest using a bigger proportion. 50%.

**Comment by chengsoonong** [comment]
For @MatthewJA education:
http://sebastianraschka.com/blog/2016/model-evaluation-selection-part2.html

**Comment by MatthewJA** [comment]
Done; do you want me to put the test set data somewhere so we're all on the same page or are you happy to generate it if you need it?

**Comment by chengsoonong** [comment]
@jbanfield needs to decide this. For the publication, it is probably useful to have a file with indices that we can add as an appendix.

**Comment by MatthewJA** [comment]
Okay. We should probably have some procedure for storing all of the data used somewhere so that results are easily reproducible.

Perhaps it would be a good idea to do this after all plots etc. are finalised, so we can run one script or notebook that generates everything in one go (including the test indices).
