### ISSUE TITLE
Write up summary of fields

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#149]
#108

Here's a map of SWIRE, for reference:

![image](https://cloud.githubusercontent.com/assets/2681312/17688041/95bb889e-63be-11e6-893b-a34a2a864519.png)

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/17688078/fe6f2b34-63be-11e6-83de-62a64eec6340.png)

Coverage of EMU (from Norris et al. (2011)).

**Comment by MatthewJA** [comment]
![skymap](https://cloud.githubusercontent.com/assets/2681312/18462850/36c9ed5a-79c9-11e6-9077-b5e58516ed99.png)

Best I can do for a plot of the fields, I think.

**Comment by chengsoonong** [comment]
Looks good.

Please indicate in the caption describing this figure in your thesis which ones are radio, and which are optical.
