### ISSUE TITLE
host counting error

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#15]
The function consensus in notebook potential_host_counting dies because the kernel density estimator gets a singular matrix.

I suspect it is due to the following warning:
/Users/cong/anaconda3/lib/python3.4/site-packages/scipy/stats/kde.py:503: RuntimeWarning: invalid value encountered in sqrt
  self._norm_factor = sqrt(linalg.det(2_pi_self.covariance)) \* self.n
/Users/cong/anaconda3/lib/python3.4/site-packages/scipy/stats/kde.py:214: RuntimeWarning: overflow encountered in exp
  result = result + exp(-energy)

**Comment by MatthewJA** [comment]
Will be resolved by #16.
