### ISSUE TITLE
Write up motivations

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#150]
Also going to drop a link here to Kyle Willett's [talk on the Radio Galaxy Zoo](https://speakerdeck.com/willettk/radio-galaxy-zoo-host-galaxies-and-radio-morphologies-for-large-surveys-from-visual-inspection) from last year. Could be useful reference.

**Comment by jbanfield** [comment]
This may be helpful.  The [repository of all RGZ papers](http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?library&libname=RGZ+Papers&libid=5612f5449d).
