### ISSUE TITLE
Check I'm using the right WISE catalogue

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#152]

**Comment by jbanfield** [comment]
I think we checked this at our last coffee meeting.  Or is this something new?

**Comment by MatthewJA** [comment]
Yup, this is all good on your end. I just have to make sure that the catalogue I'm using matches the one we checked at the last meeting.

**Comment by MatthewJA** [comment]
For future reference, it's the AllWISE catalogue (which I had to redownload anyway for FIRST).
