### ISSUE TITLE
Make many violin/vertical scatter plots

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#156]

**Comment by MatthewJA** [comment]
![plot](https://cloud.githubusercontent.com/assets/2681312/18079460/2f90a6f0-6ed4-11e6-9fbf-9c2a1aee0d5b.png)

Looks alright!

**Comment by chengsoonong** [comment]
One of many rules for good plots: Fix the y-axis such that it is the same for all your plots. Default choice is 70-100, unless you have good reason to tweak it.

**Comment by MatthewJA** [comment]
Ah, good point. Added explicit bounds in 3e34472. Thanks!

**Comment by MatthewJA** [comment]
Things to trial:
- LR on all three label sets
- LR on raw RGZ labels
- Yan 2010 with constant η (Izbicki & Stern, 2013 - 10.1002/sam.11206; kinda similar to Raykar 2010 but I think ultimately different)
- Raykar 2010
- Yan 2010 with clustering
- Yan 2010 with PCA in the annotator model

I think that's all.

**Comment by chengsoonong** [comment]
On a separate plot, compare logistic regression with random forest on the Norris and Fan labels.

**Comment by MatthewJA** [comment]
I'll do that right now, since it should be pretty straightforward. I can't figure out a non-pickle way to serialise RF, so I'll just not serialise RF. Another point for LR...

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/18190935/8963718a-7109-11e6-93be-b8d59839d2ad.png)

**Comment by MatthewJA** [comment]
Raw label experiment in d91dd2b. Surprisingly bad (50% balanced accuracy) so maybe I need to regularise more or something.

**Comment by MatthewJA** [comment]
Going to split these into different issues!

**Comment by chengsoonong** [comment]
Please add these plots as you do them to your thesis. Start a folder called "figures" and add the plots there. Update the LaTeX such that you have the plots displayed as figures and write enough words in the caption such that it is clear what the plot demonstrates, e.g. Logistic Regression performs better than Random Forest on both ground truth labels.

I suggest adding a path to configuration that points to the "figures" folder, and write your PDFs directly there from matplotlib.
