### ISSUE TITLE
Raw data on cloudstor

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#172]
It would be useful to have the raw data available to share. How about adding it to ANU cloudstor?

https://cloudstor.aarnet.edu.au

@jbanfield might need to do this, if @MatthewJA does not have enough rights as a student.
- ATLASDR3_cmpcat_23July2015.dat.gz
- cdfs_11JAN2014_2x2_5x5.tgz
- sanitized_radio_2016-03-01.tar.gz
- RGZ-ATLAS-Bookkeeping.csv

**Comment by jbanfield** [comment]
Can do.  Although cloudstor has an expiry date.

**Comment by chengsoonong** [comment]
Do you have suggestions on how to share private data?
Another option is a gitlab git lfs, which seems overkill for this.

I also just noticed that there seems to be different instructions online. More files:
- SWIRE3_CDFS_cat_IRAC24_21Dec05.tbl.gz or an AllWISE catalogue covering the CDFS field
- norris_2006_atlas_classifications_ra_dec_only.dat (pipe-separated RA/DEC from Norris et al. (2006) Table 6)
- wise_allwise.wise_allwise_p3as_psd4511.tbl
- fan_2015_swire_only.csv

@MatthewJA could you please check why docs/setup.md is different from http://crowdastro.readthedocs.io/en/latest/setup/

**Comment by MatthewJA** [comment]
On it! They should be the same unless the hook has broken...

**Comment by MatthewJA** [comment]
Build failing as of 9bd5e390147107625028a2a86e684ea36f38500a. Tests are failing too. I'll fix it.

edit: All working now! Also, I believe GitLab only lets you have 10 GB files (I think we have more than that?)

**Comment by jbanfield** [comment]
cloudstor only has an expiry date for email links.  uploading the data now.

**Comment by jbanfield** [comment]
all set up except for the sanatised_radio files.  You should have access to modify the directory.

**Comment by chengsoonong** [comment]
I only see 3 files. @jbanfield could you share it with my login (chengsoon.ong@anu.edu.au), instead of an email link?

**Comment by MatthewJA** [comment]
Just updating this issue.

**Comment by chengsoonong** [comment]
![screen shot 2016-09-13 at 9 29 41 am](https://cloud.githubusercontent.com/assets/709424/18456501/c69aba16-7994-11e6-990f-bfbc232bcd2d.png)

**Comment by MatthewJA** [comment]
Ah, just realised I actually have permissions to upload files here! Sorry for the wait.

Uploaded the rest of the data.

**Comment by chengsoonong** [comment]
Missing data/CDFSmosaic_allch_8March2015.fits

**Comment by MatthewJA** [comment]
Added.

**Comment by chengsoonong** [comment]
Do we need the file in crowdastro.json called radio_galaxy_zoo_db?

**Comment by MatthewJA** [comment]
Yes, that's the MongoDB database. It's not an actual file (possibly this is unclear since the rest of those strings are paths).
