### ISSUE TITLE
Plot Yan variants against Raykar

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#175]
- Yan
- Yan PCA
- Yan clustering
- Yan η_t
- Yan η
- Raykar

**Comment by MatthewJA** [comment]
So this is Yan against the breast cancer dataset. 20 trials, 5 random restarts, 35% hidden labels.

![yan](https://cloud.githubusercontent.com/assets/2681312/18469158/6527f3d8-79ea-11e6-9805-fd32daed87aa.png)

Compared to Raykar:

![raykar](https://cloud.githubusercontent.com/assets/2681312/18469181/7b51c742-79ea-11e6-9b76-07d9b2f70091.png)

The results from Yan are considerably worse.

**Comment by chengsoonong** [comment]
Your results are not so informative. I suspect this is because you are trying to solve a problem that is not linearly separable (no kernel for your logistic regression), and the dataset needs a kernel.

I suggest using a1a and a2a:
https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html

Alternatively. Take the data (any one from a?a), merge the training and test sets, and split it like you do above.

**Comment by MatthewJA** [comment]
I forgot to mention: I'm simulating crowd labellers (T = 5) with the same simulated true positive/false positive rates as for the Raykar algorithm. This may play against the assumptions made by the Yan algorithm. I'll rerun this with clustering to determine regions of labeller accuracy, see how that goes, and then I'll try a1a. Note that I will still have to simulate the crowd labelling.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/18498014/6ab7e45c-7a76-11e6-864d-426f35fcaf3a.png)

There's the same test with different crowd labelling mechanics (clustering, i.e., data dependent). I'll try a1a/a2a next.

**Comment by chengsoonong** [comment]
There are three different LR, not clear which one you are reporting:
1. LR using ground truth labels
2. LR using all the crowd labels
3. LR using the majority vote crowd labels

**Comment by MatthewJA** [comment]
Ah, sorry, it's LR with majority vote.

**Comment by chengsoonong** [comment]
I suggest comparing with LR with ground truth. That way, you can account for how difficult the task for the linear classifier is. Looks like LR is working ok, so no need to try new data.

**Comment by MatthewJA** [comment]
Not sure what you mean. Comparing LR against the groundtruth (which is by definition 100%), comparing LR (majority vote) against LR (groundtruth), or something else? I think that comparing against LR trained on the groundtruth makes sense so I'll do that.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/18500293/9f66e8f2-7a89-11e6-94df-b571f85b9350.png)

The LR in the middle is LR trained on the majority vote. (I need to add a way to edit these things...)

The LR on the right is trained on the groundtruth. It does marginally better.
