### ISSUE TITLE
Compare actual annotator alpha/beta to groundtruth alpha/beta

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#182]

**Comment by MatthewJA** [comment]
Estimated alpha and beta values:
![raykaractual](https://cloud.githubusercontent.com/assets/2681312/18772016/eb507892-8186-11e6-85fd-5f860791687f.png)

Raykar alpha and beta values:
![raykarest](https://cloud.githubusercontent.com/assets/2681312/18772014/ea3102ec-8186-11e6-84d4-2dea8c9269be.png)

The Raykar algorithm assigns very high true negative rates to the labellers. Could this be due to unbalanced classes?

**Comment by chengsoonong** [comment]
Report both Pearson and Spearman correlation coefficient, in scipy.
