### ISSUE TITLE
do not overwrite 'features'

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#184]
In the workflow, it would be better to have the raw image features called something like 'raw_features' and the output of the CNN 'features' in the HDF5 file. The current mutation of the file means that it is hard to check.

Alternatively, create a second HDF5 file for training logistic regression.

Current workflow has a bug:
$ crowdastro train_cnn
Peeking into HDF5 file
Dataset: /features
         has shape (42252, 1031)
Dataset: /is_atlas_test
         has shape (2263,)
Dataset: /is_atlas_train
         has shape (2263,)
Dataset: /is_ir_test
         has shape (42252,)
Dataset: /is_ir_train
         has shape (42252,)
Dataset: /labels
         has shape (42252,)
Dataset: /positions
         has shape (42252, 2)
End file peeking
Using Theano backend.
Traceback (most recent call last):
  File "/Users/ong017/anaconda3/envs/astro/bin/crowdastro", line 11, in <module>
    load_entry_point('crowdastro', 'console_scripts', 'crowdastro')()
  File "/Users/ong017/Repo/crowdastro/crowdastro/**main**.py", line 115, in main
    subcommands[args.subcommand](args)
  File "/Users/ong017/Repo/crowdastro/crowdastro/train_cnn.py", line 95, in _main
    int(args.batch_size))
  File "/Users/ong017/Repo/crowdastro/crowdastro/train_cnn.py", line 40, in train
    (-1, 1, PATCH_DIAMETER, PATCH_DIAMETER))
ValueError: total size of new array must be unchanged

**Comment by MatthewJA** [comment]
Alright, I'll fix both of these things!

**Comment by MatthewJA** [comment]
Just ran the whole pipeline successfully! Hopefully it works for you (+ everyone else by extension), too.

**Comment by chengsoonong** [comment]
Still same error. Perhaps my configuration is wrong somehow.

**Comment by MatthewJA** [comment]
Some troubleshooting: Did you pull? What is the patch size in crowdastro.json?

**Comment by chengsoonong** [comment]
$ cat crowdastro/crowdastro.json 
{
    "data_sources": {
        "atlas_catalogue": "data/ATLASDR3_cmpcat_23July2015.dat",
        "atlas_image": "data/CDFSmosaic_allch_8March2015.fits",
        "cdfs_fits": "data/cdfs",
        "norris_coords": "data/norris_2006_atlas_classifications_ra_dec_only.dat",
        "fan_swire": "data/fan_2015_swire_only.csv",
        "radio_galaxy_zoo_db": "radio",
        "rgz_to_atlas": "data/RGZ-ATLAS-Bookkeeping.csv",
        "swire_catalogue": "data/SWIRE3_CDFS_cat_IRAC24_21Dec05.tbl",
        "wise_catalogue": "data/wise_allwise.wise_allwise_p3as_psd4511.tbl"
    },

```
"mongo": {
    "host": "localhost",
    "port": 27017
},

"surveys": {
    "atlas": {
        "fits_width": 200,
        "fits_height": 200,
        "fits_width_large": 500,
        "fits_height_large": 500,
        "web_width": 500,
        "web_height": 500,
        "click_width": 424,
        "click_height": 424,
        "distance_cutoff": 0.02,
        "scale_width": 2.1144278606965172,
        "scale_height": 2.1144278606965172,
        "mosaic_scale_x": 0.4,
        "mosaic_scale_y": 0.4
    },
    "swire": {
        "n_features": 5,
        "distance_cutoff": 0.05
    },
    "wise": {
        "n_features": 4,
        "distance_cutoff": 0.05
    }
},

"test_size": 0.2,

"patch_radius": 16
```

}

**Comment by MatthewJA** [comment]
Looks fine... are you running train_cnn before generate_cnn_outputs?

Otherwise something must be wrong with the code. What commit hash or version are you on?

**Comment by chengsoonong** [comment]
commit 4e41931cc19a9906ad7dfbcd2e6a7b70b01d64cc
was the one that didn't work.

Could you update the check raw files script to include some MD5 sum check or something? Perhaps there is some data that is different. I didn't copy files that I already had. Do not know whether some files have changed, but have retained names from the past.

**Comment by MatthewJA** [comment]
I'll see if I can run the pipeline again on that commit.

And yeah, I'll add a checksum to `import_data`.

**Comment by MatthewJA** [comment]
Alright, added some checksums. Rerunning the pipeline now myself.

**Comment by MatthewJA** [comment]
Ah, you're using SWIRE, I'm using WISE. Maybe I broke it for SWIRE and not for WISE. I'll run for SWIRE and see how it goes.

**Comment by MatthewJA** [comment]
I think I've found the problem &mdash; `training_data` has an off-by-one error. Testing my fix and then I'll push it.

**Comment by chengsoonong** [comment]
How do I choose between SWIRE and WISE?

**Comment by MatthewJA** [comment]
--ir wise

as an option to import_data.

**Comment by chengsoonong** [comment]
Confirm that both are now working for me. Excellent!
