### ISSUE TITLE
Selecting the top annotators for Raykar

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#185]
@chengsoonong suggested that I just use the the top n most prolific annotators, and compare this to the top n accurate annotators (assessed against the groundtruth). The problem is, the most prolific annotators are _really_ bad, for unknown reasons.
![rgz_raykar](https://cloud.githubusercontent.com/assets/2681312/18620900/7681eefe-7e5e-11e6-8c0d-9512cfb8e3f2.png)
Increasing n does improve accuracy (as far as I can tell, n -> 1100 behaves as expected &mdash; this algorithm actually works!) but it's _so_ slow. If I can figure out AWS, I can probably run it for longer, but I may or may not do that.

I think that assessing the annotators against something like the majority vote is a good idea. I understand the reasons for using the number of annotations (simplicity, etc.) but I think that from the results in the plot there's effectively no information gained by using this to choose the "top" n annotators.

**Comment by chengsoonong** [comment]
This is an excellent plot. Shows that one needs to identify the good annotators. Now, if issue #182 shows a scatter plot comparing annotator alpha,beta that is highly correlated with the balanced accuracy, this means that you can identify good annotators. Then you can add top-10 accurate based on alpha,beta to the above plot.

You may have to convert alpha,beta into one single number, something like F1.

**Comment by MatthewJA** [comment]
Given the alpha and beta are estimated by the algorithm, wouldn't using them to pick the top n defeat the purpose of only using the top n? Or am I misinterpreting you?

**Comment by chengsoonong** [comment]
Consider the following experiment:
1. Run Raykar on top 50 most prolific, or everyone who has labelled more than 50, or some rule that will give a good pool of annotators (approx 50).
2. Use alpha, beta to choose top 10 most accurate annotators
3. Using top 10, compare performance with ground truth.

This way, we can identify accurate annotators without ground truth, and in step 3, show that these annotators are indeed good annotators when we compare with ground truth.

**Comment by MatthewJA** [comment]
I see! I'll do that soon then.

**Comment by MatthewJA** [comment]
After discussion in the meeting today, I'll use majority vote to assess annotator quality.

Edit: Running this now! :D

**Comment by MatthewJA** [comment]
![rgz_raykar](https://cloud.githubusercontent.com/assets/2681312/18782213/af8e7fa6-81c8-11e6-9b6d-eeb115a7c613.png)

Works great.
