### ISSUE TITLE
Thesis outline

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#187]
Here's my thesis headings up to the predictors plot. Headings are indicative of content rather than the actual heading. Any comments are appreciated.
1. Astrophysics & Motivation
   1. Radio Active Galactic Nuclei
   2. Astronomical Concepts
      1. Astronomical Coordinates
      2. Flux and Magnitude
   3. Radio Surveys
      1. EMU
      2. ATLAS
      3. FIRST
   4. IR Surveys
      1. WISE
      2. SWIRE
   5. Cross-identification
      1. Motivation
      2. Norris et al.
      3. Fan et al.
   6. Radio Galaxy Zoo
2. Machine Learning
   1. Classification
      1. Logistic Regression
      2. Random Forests
   2. Image Features (CNNs)
   3. Crowdsourcing
      1. Motivation & Examples
      2. Problems
   4. Label Aggregation
      1. Majority Vote
      2. Weighted Majority Vote
      3. Raykar et al.
      4. Yan et al.
3. Cross-identification
   1. Formalism
      1. Object Localisation
      2. Galaxy Classification Task
   2. Feature Selection
      1. Astronomical Features
      2. Image Features and Filters
   3. Binary Classification Model
   4. Crowd Labels
      1. Majority Vote
      2. Raykar et al.
   5. Results
   6. Discussion

**Comment by chengsoonong** [comment]
Add a list of where your results plots (figures) are going to go. This helps to figure out dependencies. It is best just to implement the above into the LaTeX file, and add figure captions (with blank figures if necessary).

**Comment by MatthewJA** [comment]
Alright, I'll do that. I've added the outline in 1c15652c810cbaf1c1e4ff596f9a3994728bb1ba and e37f07682f588fa6641d853d657733875217bfac.
