### ISSUE TITLE
Update the GitHub repo description

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#188]
I think it might be a good idea to update the GitHub description, now that this project has existed for a while. It's currently "Machine learning using crowd sourced data in astronomy". Given that the first line of the readme is "This project aims to develop a machine learned method for cross-identifying radio objects and their host galaxies, using crowdsourced labels from the Radio Galaxy Zoo.", I would suggest "Cross-identification of radio objects and host galaxies using crowdsourced training labels."

If the scope of this repo is to change later, then it could be updated again later, but I think being more specific is a good idea for now.

**Comment by chengsoonong** [comment]
Updated
