### ISSUE TITLE
Investigate CNN features

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#19]
Use Caffe/Barista.

**Comment by chengsoonong** [comment]
Use the tutorial CNN of keras.io

**Comment by MatthewJA** [comment]
Made the tutorial CNN [here](https://github.com/chengsoonong/crowdastro/blob/master/notebooks/14_cnn.ipynb) and looked at the results [here](https://github.com/chengsoonong/crowdastro/blob/master/notebooks/15_cnn_test.ipynb).
