### ISSUE TITLE
Implement SWIRE colour-colour features

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#195]
If I am going to use SWIRE in my thesis, then I should use similar features to those I'm using for WISE. Two of the features I'm using for WISE are the colour-colour features, i.e. w1 - w2 and w2 - w3.

@jbanfield: What would be the equivalent for SWIRE? I believe it should be the ratios 3.6 µJy / 4.5 µJy and 4.5 µJy / 5.8 µJy - is this correct? (I haven't had much luck finding SWIRE colour-colour diagrams to work off.)

**Comment by jbanfield** [comment]
Yes, that is the equivalent.  

There is a SWIRE colour plot (Fig. 5) in [Banfield+(2011)](http://adsabs.harvard.edu/abs/2011ApJ...733...69B).  It uses the 8.0um wavelength too.

**Comment by MatthewJA** [comment]
Thanks! I'll add those as features before doing any SWIRE experiments.
