### ISSUE TITLE
The effect of WISE features on predicted probability

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#198]
Basically no effect. I think this is a little bit suspicious, so I'm going to try out the normalisation and see if that changes things before I resolve this issue.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/19150095/ca16564e-8c10-11e6-8c09-a1c15afbfc69.png)

These are really hard to interpret, though, because there's a lot of stuff going on. Not sure how to remedy that (maybe a heatmap?)

**Comment by chengsoonong** [comment]
Plot circles, with alpha=0.1 or something like that. This simulates a heatmap without actually needing to do any fiddly density estimation.

Features quite useful actually. There are red objects which was easily separated by using the difference features (I'm assuming z is the target label). One would not expect all objects to be easily separated.

**Comment by MatthewJA** [comment]
Do you think it's worth including this in the thesis, given the feature ablation experiment?

**Comment by chengsoonong** [comment]
These plots are useful for astronomers who have been staring at magnitude data for many years. Just add plots, and refer to the feature ablation section for the effect on predictive performance.

**Comment by MatthewJA** [comment]
Ah, right. I'll do that then!

**Comment by jbanfield** [comment]
it may be easier for astronomers to see the W1 - W2 & W2-W3 colour magnitude diagram.  Change the colour of the symbol to the probability.

**Comment by MatthewJA** [comment]
I'll plot that and see how it looks.

**Comment by MatthewJA** [comment]
Colour-based probability is really hard to interpret.

![image](https://cloud.githubusercontent.com/assets/2681312/19501876/a1849b94-95f4-11e6-94ef-58cc7a2853d2.png)

(I've used a sequential colourmap here, but the principle still seems to apply for other colourmaps.)

Just plotting whether it's classified positive or negative seems to look better:
![image](https://cloud.githubusercontent.com/assets/2681312/19501930/28f91d5c-95f5-11e6-95ee-19e54b805ee5.png)

Hexbin is far more friendly though:
![image](https://cloud.githubusercontent.com/assets/2681312/19502149/89241122-95f6-11e6-9a37-05b6b03145de.png)

**Comment by MatthewJA** [comment]
Note that this is a biased sample: The only negative examples included are near an AGN.

**Comment by jbanfield** [comment]
in the hexbin plot, yellow is high ?

low probability of containing an AGN is blueish in colour?  then the sources near (0,0)-(2,0) make sense as these are supposed to be star forming galaxies like spirals as these should not have AGN.

**Comment by MatthewJA** [comment]
Yes, yellow is high and blue is low. (Sorry, should have included a scale).

It's not probability though, it's density of sources above a certain probability (in this case, 0.5). It happens to be the case that almost all the >0.5 sources have >0.75 probability, though, so this histogram is probably a decent proxy for an ideal probability plot.

Left is >0.5 (predicted AGN), right is <0.5 (predicted non-AGN).

**Comment by MatthewJA** [comment]
Since we have a linear model, there's no cross-dependence of terms. That means we should just be able to throw the magnitude differences into the model and see what it outputs as probabilities, ignoring all other features. We get this:

![image](https://cloud.githubusercontent.com/assets/2681312/19503315/6ce8d47c-95fe-11e6-9c13-aaf32f4a7444.png)

This kinda explains two things.
- We know that the magnitude difference &ndash; AGN relationship is nonlinear, so a linear map won't do terribly well and this may be why our performance with just magnitudes is poor.
- Switching from magnitudes to linear units seemed to improve performance, which may be because it lets this kind of decision boundary happen.

**Comment by MatthewJA** [comment]
Resolved in 2a8c136.
