### ISSUE TITLE
Investigate normalisation and scaling of feature blocks

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#199]
See if this changes the effect of WISE features on predicted probabilities! #198

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/19151621/5e6b8438-8c19-11e6-9581-aa593816dac1.png)

Hmm.

**Comment by chengsoonong** [comment]
Looks like scaling only has small effect. I suggest closing this issue for now, and revisit it if you find some obvious problem in your Raykar implementation (by testing with flipped labels).
