### ISSUE TITLE
Using raw labels to train directly

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#207]
Currently writing a section on feeding raw labels to logistic regression directly, ignoring the label noise (even though this doesn't work in practice for RGZ). I can't seem to find any resources on this method of dealing with repeated labels. Does it have a common name or any useful keywords?

**Comment by chengsoonong** [comment]
Add a paragraph discussing that this didn't work in your implementation, at the end of Section 4.6.
