### ISSUE TITLE
RGZ data use

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#208]
@jbanfield: What are the acknowledgement requirements for the use of the Radio Galaxy Zoo data? I assume I must link to http://rgzauthors.galaxyzoo.org/ but is there a specific statement I should use? (Apologies if this is listed somewhere &mdash; I can't find it.)

**Comment by jbanfield** [comment]
Something like this:

> This thesis had been made possible by the participation of more then 10,000 volunteers in the Radio Galaxy Zoo project.  Their contributions are individually acknowledged at http://rgzauthors.galaxyzoo.org. 

If you used astropy, there needs to be a line something like

> This thesis made use of astropy, a community-developed core python package for astronomy (Astropy Collaboration et al. 2013).

REF: [Astropy Collaboration et al., 2013, A&A, 558, A33](http://adsabs.harvard.edu/abs/2013A%26A...558A..33A)

**Comment by MatthewJA** [comment]
Thanks! Resolved in 3c408f1.
