### ISSUE TITLE
Classifier without CNN features

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#210]
Check whether there is again a big drop in performance when training on CDFS and testing on ELIAS.

**Comment by MatthewJA** [comment]
To confirm what you mean: Using just magnitude features, train on CDFS and test on ELAIS, then compare against Middelburg (Norris equivalent for ELAIS)?

**Comment by chengsoonong** [comment]
Was just discussing with Julie after your seminar about the worrying result from last Friday. To be left for after thesis is submitted.

**Comment by chengsoonong** [comment]
Features: Magnitude, distance, everything except CNN.

**Comment by MatthewJA** [comment]
No big drop in performance. ~78.0% CDFS -> ~75.5% ELAIS.
