### ISSUE TITLE
Pixel scale

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#25]
How do we deal with big vs small sources (in terms of number of pixels)?

**Comment by MatthewJA** [comment]
Perhaps we could use multiple window sizes, as suggested by the computer vision people.

Note that there's some really big radio jets out there and some of them span multiple images, so we definitely can't catch all of them anyway.

**Comment by MatthewJA** [comment]
Increasing the image patch radius from 40 px to 60 px increases logistic regression classification accuracy by 1.55 percentage points, and random forest classification accuracy by 0.89 percentage points.

**Comment by MatthewJA** [comment]
Closing and merging with #77 and #95.
