### ISSUE TITLE
Specify how to aggregate set of active learning

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#32]
For each image, we get a set of "uncertainties" for each patch which contains a potential host. How do we combine this into an image level "uncertainty".

**Comment by MatthewJA** [comment]
I've tried an entropy approach in [17_training_with_features](https://github.com/chengsoonong/crowdastro/blob/master/notebooks/17_training_with_features.ipynb). The subject with the highest entropy does look hard to classify and it's clear there's a lot of uncertainty in the result.

**Comment by MatthewJA** [comment]
Probably the oldest issue I'm going to bump... I should consider testing whether difference between the top two predicted probabilities is a good way to aggregate the uncertainties.

**Comment by MatthewJA** [comment]
This should be discussed in the thesis.

**Comment by MatthewJA** [comment]
Resolved!
