### ISSUE TITLE
Can we use the WISE or SWIRE source catalogues to find potential hosts and their astronomical features?

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#33]

**Comment by MatthewJA** [comment]
[Notebook #13](https://github.com/chengsoonong/crowdastro/commit/73dbf21577357dc30bf309e6d3446779ee749368)

The answer is "yes", but I'm not sure if it's a better idea than blob detection on the image itself. I get pretty dramatically different results depending on the survey &mdash; I should ask Julie if she has any insight on which survey I ought to use.

I haven't yet investigated features of the potential hosts. I'll do that once I have a solid classification pipeline going.

**Comment by chengsoonong** [comment]
Please fill https://github.com/chengsoonong/crowdastro/wiki/astro-questions

**Comment by MatthewJA** [comment]
Done.

**Comment by MatthewJA** [comment]
Julie said to use the SWIRE catalogues for ATLAS data. I did this in [13_source_catalogue](https://github.com/chengsoonong/crowdastro/blob/master/notebooks/13_source_catalogue.ipynb).
