### ISSUE TITLE
Proportions of source types

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#35]
- compact
- multiple compact
- complex jets

**Comment by chengsoonong** [comment]
Report performance for each type separately.

**Comment by MatthewJA** [comment]
Interesting preliminary results from the catalogue: There are very, very few hosts in the ATLAS data with more than one radio component. I'm not sure if this is a) a quirk of ATLAS, b) a quirk of my code for generating the catalogue, or c) a general property.

**Comment by chengsoonong** [comment]
Where is this result?
What are the numbers for compact and others?

I suspect this is a quirk of ATLAS, which we can check with some more computation on the non ATLAS catalogue. Let us assume that it it not a code problem for now.

**Comment by jbanfield** [comment]
Yes, ATLAS is mainly compact objects.  The rest of the database (non-ATLAS) is only 5% compact.

**Comment by MatthewJA** [comment]
I can now pitch in that just over 1000 hosts appear by themselves in subjects (i.e., do not have the "multiple hosts" problem).

Great to know that ATLAS is mainly compact.

**Comment by MatthewJA** [comment]
Just realised that I can pull this information from the Norris catalogue!

**Comment by chengsoonong** [comment]
Leave this for later. Reader can look at Norris catalogue.
