### ISSUE TITLE
path to data

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#37]
There is a folder called data in the repository. Not sure what this is.

Also, for the repository crowdastro-data, we should just use a soft-link to point to it. Then paths in the notebooks can be ../crowdastro-data.

**Comment by MatthewJA** [comment]
https://github.com/chengsoonong/crowdastro/blob/master/docs/setup.md

Agreed on the soft link.

**Comment by MatthewJA** [comment]
We should probably just wrap every data access with the `crowdastro` module. I can get rid of the dependency on `gator_cache.sqlite` now, so this will be much easier to do.

**Comment by MatthewJA** [comment]
Should be resolved in the rework branch. Will merge soon, #58
