### ISSUE TITLE
Cannot extract training data in 14_cnn

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#38]
The exact location this happens seems to be moving around (perhaps due to mongoDB not always returning things in the same order).

Error message below:

Extracting training data from ATLAS subject #94
Extracting training data from ATLAS subject #95
## Extracting training data from ATLAS subject #96

KeyError                                  Traceback (most recent call last)
/Users/cong/anaconda3/lib/python3.4/site-packages/astropy/utils/decorators.py in **get**(self, obj, owner)
    512         try:
--> 513             return obj.**dict**[self._key]
    514         except KeyError:

KeyError: 'data'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-23-aedf32faed58> in <module>()
      6     potential_hosts = get_potential_hosts(subject)
      7     true_hosts = {tuple(i) for i in get_true_hosts(subject, potential_hosts, conn).values()}
----> 8     patches, classifications = zip(*get_training_data(subject, potential_hosts, true_hosts))
      9     training_inputs.extend(patches)
     10     training_outputs.extend(classifications)

<ipython-input-7-ea862900f587> in get_training_data(subject, potential_hosts, true_hosts)
      1 def get_training_data(subject, potential_hosts, true_hosts):
----> 2     radio_image = crowdastro.data.get_radio(subject, size='5x5')
      3 
      4     training_data = []
      5     radius = 40

/Users/cong/Repo/crowdastro/crowdastro/data.py in g(subject, _args, *_kwargs)
     27             raise ValueError('Subject not from ATLAS survey.')
     28 
---> 29         return f(subject, _args, *_kwargs)
     30 
     31     return g

/Users/cong/Repo/crowdastro/crowdastro/data.py in get_radio(subject, size)
    129 
    130     with open_fits(subject, field, 'radio', size=size) as fits_file:
--> 131         return fits_file[0].data
    132 
    133 @require_atlas

/Users/cong/anaconda3/lib/python3.4/site-packages/astropy/utils/decorators.py in **get**(self, obj, owner)
    513             return obj.**dict**[self._key]
    514         except KeyError:
--> 515             val = self.fget(obj)
    516             obj.__dict__[self._key] = val
    517             return val

/Users/cong/anaconda3/lib/python3.4/site-packages/astropy/io/fits/hdu/image.py in data(self)
    206             return
    207 
--> 208         data = self._get_scaled_image_data(self._data_offset, self.shape)
    209         self._update_header_scale_info(data.dtype)
    210 

/Users/cong/anaconda3/lib/python3.4/site-packages/astropy/io/fits/hdu/image.py in _get_scaled_image_data(self, offset, shape)
    619         code = BITPIX2DTYPE[self._orig_bitpix]
    620 
--> 621         raw_data = self._get_raw_data(shape, code, offset)
    622         raw_data.dtype = raw_data.dtype.newbyteorder('>')
    623 

/Users/cong/anaconda3/lib/python3.4/site-packages/astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)
    566                               offset=offset)
    567         elif self._file:
--> 568             return self._file.readarray(offset=offset, dtype=code, shape=shape)
    569         else:
    570             return None

/Users/cong/anaconda3/lib/python3.4/site-packages/astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)
    257                 memmap = Memmap(self._file,
    258                                 mode=MEMMAP_MODES[self.mode],
--> 259                                 dtype=np.uint8)
    260 
    261                 # Now we immediately discard the memmap array; we are really

/Users/cong/anaconda3/lib/python3.4/site-packages/numpy/core/memmap.py in **new**(subtype, filename, dtype, mode, offset, shape, order)
    258         bytes -= start
    259         offset -= start
--> 260         mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
    261 
    262         self = ndarray.**new**(subtype, shape, dtype=descr, buffer=mm,

OSError: [Errno 24] Too many open files

**Comment by MatthewJA** [comment]
With the README now pushed, see if you can reproduce this error on the command line. I suspect NumPy behaves differently on our different platforms, which is mildly terrifying (but probably solvable). It may be the case that I have more RAM and thus NumPy resorts to memory mapping on your computer, failing in the process. If this is the case then I may need to explicitly memory map to get around the issue.

**Comment by MatthewJA** [comment]
Ah, I managed to trip this on Windows, though with a different error message. I think the way I was dealing with the files broke Python's GC. Will be fixed in `train_cnn.py`.

**Comment by MatthewJA** [comment]
Should be fixed in `train_cnn.py`? Given I haven't heard complaints and it's been running for days, I am going to close this.
