### ISSUE TITLE
model.layers[2].get_output() not working

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#39]
This does not seem to be a defined function. Perhaps a better way would be to use get_layer(), and then use output.

The attached seems to work (not sure why you need this output).

<img width="1002" alt="screen shot 2016-05-02 at 23 05 11" src="https://cloud.githubusercontent.com/assets/709424/14955074/a041011a-10ba-11e6-9f11-cbc8cdd3dce5.png">

**Comment by chengsoonong** [comment]
Documentation from keras:
http://keras.io/layers/about-keras-layers/

**Comment by MatthewJA** [comment]
I had some problems with this - I might need to update Keras. What version are you on?

**Comment by chengsoonong** [comment]
I think the difference is between theano and tensorflow, but that is just a guess.

In [1]: import keras
Using TensorFlow backend.

In [2]: keras.**version**
Out[2]: '1.0.2'

**Comment by MatthewJA** [comment]
Cleaning this up, I had an outdated version of Keras. Merging into #46; #58
