### ISSUE TITLE
Cast host galaxy problem as binary classification task

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#4]
Can the location of host galaxy be expressed as a binary classification problem?

**Comment by chengsoonong** [comment]
How many potential sources (hosts) are there in each image? Choose brightness threshold to be a little bit below the dimmest confidently labelled example.

**Comment by MatthewJA** [comment]
I'm pretty happy to close this one now. Finding potential hosts and then classifying each as either the true host or not seems a good approach, and we can get the number of potential hosts down to ~50 &ndash; 80, which is feasible for the classification task. It also seems that scikit-image's blob detection will suit for finding potential hosts.

**Comment by chengsoonong** [comment]
In general, it would be great if you could add a pointer to a commit when closing issues. Something like, "the file blib.tex contains a description in commit blah."

**Comment by MatthewJA** [comment]
Can do!

For this issue in particular, the notebook on potential host detection is [here](https://github.com/chengsoonong/crowdastro/blob/master/notebooks/10_potential_host_detection.ipynb) and the binary classification problem is looked at [here](https://github.com/chengsoonong/crowdastro/blob/master/notebooks/9_pipeline.ipynb).
