### ISSUE TITLE
Train CNN on a GPU

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#45]
I've separated the CNN code into some independent modules. This is documented in the [README](https://github.com/chengsoonong/crowdastro/blob/master/README.md).

Run everything up to "Train the CNN" to get the data needed for training the CNN.  `training.h5` and `model.json` are the data dependencies for the actual training step. These will be ~4 GB total. Then the "Train the CNN" step can be run on the GPU.

**Comment by chengsoonong** [comment]
I do not seem to have model.json, or more accurately, I do not know how to generate one.

**Comment by MatthewJA** [comment]
> Generate a model:
> `crowdastro/compile_cnn.py model.json`

From the [README](https://github.com/chengsoonong/crowdastro/blob/master/README.md).

You'll also have to run preprocess_cnn_images.py to get the training inputs/outputs; details are also in the README.

**Comment by chengsoonong** [comment]
I need some help debugging...

crowdastro cong$ python crowdastro/compile_cnn.py model.json
Using TensorFlow backend.
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x116ccbeb8>>
Traceback (most recent call last):
  File "/Users/cong/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 140, in **del**
  File "/Users/cong/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 137, in close
UnboundLocalError: local variable 'status' referenced before assignment
mreid-thunderbolt:crowdastro cong$ python
Python 3.4.4 |Anaconda 2.3.0 (x86_64)| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import keras
> > > Using TensorFlow backend.
> > > keras.**version**
> > > '1.0.2'

**Comment by MatthewJA** [comment]
I'm not sure what could be causing that. That's coming from TensorFlow. Can you try Theano?

**Comment by chengsoonong** [comment]
Theano works.

**Comment by MatthewJA** [comment]
I wonder if it's a bug in Keras?

**Comment by chengsoonong** [comment]
Here's the weights after training for about 15 minutes on the GTX 980. 10 epochs. Training using tensorflow.
Loss about 8.5e-6

[weights.h5.zip](https://github.com/chengsoonong/crowdastro/files/273867/weights.h5.zip)

.

**Comment by MatthewJA** [comment]
Cool, that looks similar to my own results for short numbers of epochs. Could we increase the number of epochs? I used ~100 to get my previous filters, though your mileage may vary.

**Comment by chengsoonong** [comment]
The problem with keras and Tensorflow seems to have gone away for compile_cnn.py

**Comment by chengsoonong** [comment]
After about 2 days of training, the loss is 1.085e-7.

[weights_2000epochs.h5.zip](https://github.com/chengsoonong/crowdastro/files/276648/weights_2000epochs.h5.zip)

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/15457906/29df4aa0-20d6-11e6-81d6-228b84c03003.png)

These look a lot less smooth than I'd expect. Compare to my 100 epoch trial (~6 CPU hours):

![image](https://cloud.githubusercontent.com/assets/2681312/15457912/3fa6e6ae-20d6-11e6-9462-2a6b0acc34e8.png)

Out of curiosity: What batch size are you using?

**Comment by chengsoonong** [comment]
Batch size 100.

**Comment by chengsoonong** [comment]
Double check that the weights are giving the small loss as reported by the training algorithm.

**Comment by MatthewJA** [comment]
Hmm, I'm getting values of ~0.9. Going to test my old weights now.

**Comment by MatthewJA** [comment]
I get ~0.7 on my old weights. Maybe I'm misinterpreting the output of `evaluate`?

**Comment by MatthewJA** [comment]
It would be good to try running ~100 epochs with the new training data code.

**Comment by chengsoonong** [comment]
Broken somewhere else now:

$ python3 -m crowdastro consensuses processed.db classifications --atlas
Traceback (most recent call last):.00%)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cong/Repo/crowdastro/crowdastro/__main__.py", line 98, in <module>
    sys.exit(main())
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 95, in main
    args.func(args)
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 16, in consensuses
    atlas=args.atlas)
  File "/Users/cong/Repo/crowdastro/crowdastro/labels.py", line 506, in freeze_consensuses
    get_subject_consensus_kde(subject, conn, consensus_table))
  File "/Users/cong/Repo/crowdastro/crowdastro/labels.py", line 93, in get_subject_consensus_kde
    classifications = list(cur.execute(sql, [str(subject['zooniverse_id'])]))
sqlite3.OperationalError: no such column: full_radio_signature

**Comment by MatthewJA** [comment]
Try running `crowdastro classifications` first. I haven't changed anything there, so it should still work, but that's what the error is telling me.

**Comment by chengsoonong** [comment]
Ran from the top. Still broken. I am not so happy to be doing this kind of "git pull; run till crash" testing. We should discuss next week whether there are ways to avoid it.

ChengMac:crowdastro cong$ python3 -m crowdastro raw_classifications processed.db classifications --atlas
WARNING: FITSFixedWarning: PC001001= 1.000000000000E+00 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC002001= 0.000000000000E+00 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC001002= 0.000000000000E+00 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: PC002002= 1.000000000000E+00 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
ChengMac:crowdastro cong$ ss: 2459 (99.96%)
ChengMac:crowdastro cong$ python3 -m crowdastro consensuses processed.db classifications --atlas
Traceback (most recent call last):.00%)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cong/Repo/crowdastro/crowdastro/__main__.py", line 98, in <module>
    sys.exit(main())
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 95, in main
    args.func(args)
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 16, in consensuses
    atlas=args.atlas)
  File "/Users/cong/Repo/crowdastro/crowdastro/labels.py", line 506, in freeze_consensuses
    get_subject_consensus_kde(subject, conn, consensus_table))
  File "/Users/cong/Repo/crowdastro/crowdastro/labels.py", line 93, in get_subject_consensus_kde
    classifications = list(cur.execute(sql, [str(subject['zooniverse_id'])]))
sqlite3.OperationalError: no such column: full_radio_signature
ChengMac:crowdastro cong$ git log -n 1
commit 28ba95c00a9542dc5e20e7b50fb0ef84ceb410ce
Merge: 06afa84 ebb08f1
Author: MatthewJA matthew.alger@gmail.com
Date:   Wed May 25 17:09:38 2016 +1000

```
Merge branch 'master' of github.com:chengsoonong/crowdastro
```

**Comment by MatthewJA** [comment]
Huh, that's really strange. That definitely shouldn't be happening and doesn't happen locally for me.

> I am not so happy to be doing this kind of "git pull; run till crash" testing. 

Yeah, I definitely agree &mdash; I'll make some kind of integration tests ASAP.

**Comment by chengsoonong** [comment]
Using the command line sqlite3, I confirm that the processed.db database does not contain the columns that you need. You probably forgot to push something from raw_classifications step.

$ sqlite3 processed.db 
SQLite version 3.9.2 2015-11-02 18:31:45
Enter ".help" for usage hints.
sqlite> .tables
classifications  consensuses  
sqlite> .schema 
CREATE TABLE consensuses (zooniverse_id TEXT, radio_signature TEXT, source_x REAL, source_y REAL, radio_agreement REAL, location_agreement REAL);
CREATE TABLE classifications (zooniverse_id TEXT, radio_signature TEXT, source_x REAL, source_y REAL, radio_agreement REAL, location_agreement REAL);

**Comment by chengsoonong** [comment]
I think I figured out what the bug is. I did a wrong fix to the README. Testing now.

**Comment by chengsoonong** [comment]
It was a bug in the README, wrong table name. Fixed in b0c3b4f

**Comment by chengsoonong** [comment]
However, there seems to be something wrong with training_data procedure now, as it creates an empty training.h5 file.

**Comment by MatthewJA** [comment]
Regarding the tables names and command-line arguments, you're absolutely right &mdash; these should be defaults to avoid mixing things up. I'll fix that when I move onto training data generation (currently I am rewriting the data import so that it makes sense and is well-documented, on the [rework branch](/chengsoonong/crowdastro/tree/rework)). I can't see a reason why `training_data` should fail unless `consensuses` hasn't run or the corresponding table is empty, but I'll investigate it soon.

**Comment by MatthewJA** [comment]
Evidently there are a few bugs here that I wasn't encountering, though. I'll run it all through myself in a clean clone and see how it goes, then let you know. I don't want you to be wasting much time on trying to get code working &mdash; that's my job!

**Comment by chengsoonong** [comment]
The raw_classifications procedure returns an empty processed.db.

I'll leave this to you :-)

**Comment by chengsoonong** [comment]
With 42k examples, training takes longer. 10 epochs with batch size 300.

[weights_10epochs.h5.zip](https://github.com/chengsoonong/crowdastro/files/285867/weights_10epochs.h5.zip)

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/15606104/578bc5da-244d-11e6-9435-d205276dcde8.png)

These look a bit better than the old ones (and indeed seem to get better performance on the classification task).

**Comment by chengsoonong** [comment]
Let's close this issue. The refactored code seems to be working fine.
