### ISSUE TITLE
Heatmap of the sky

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#48]
It is useful to show the distribution of data, e.g. galaxies, AGNs, etc.

See Section 2.4 for the coordinate system, using the Molleweide projection:
https://github.com/chengsoonong/mclass-sky/blob/master/projects/alasdair/thesis/tran15honours-thesis.pdf

See plot_hex_map for how to show the densities, given ra,dec coordinates
https://github.com/chengsoonong/mclass-sky/blob/master/mclearn/viz.py

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/15461968/9b943f30-2102-11e6-96c6-72c375518237.png)

I think the field is a bit small to use here...

**Comment by MatthewJA** [comment]
Here's a heatmap that's just a histogram with 500 bins and a 2σ Gaussian convolution:
![image](https://cloud.githubusercontent.com/assets/2681312/15462389/e44707e6-2105-11e6-9f3b-a2091f9aac40.png)

**Comment by chengsoonong** [comment]
Could you raise an issue on mclass-sky about plot_hex_bin not working?

**Comment by MatthewJA** [comment]
No, it works fine &mdash; we're just dealing with a really small patch of the sky. (Also, Julie confirmed that we do only have the CDFS field, not ELAIS-S1.)
