### ISSUE TITLE
Find numbers

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#49]
![image](https://cloud.githubusercontent.com/assets/2681312/15461335/8f50f506-20fd-11e6-82f2-cb3c8e8fd1d7.png)

How many elements are in each of these sets?

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/15463414/9cae2a3e-210c-11e6-8689-f9fba8b7819f.png)

Best I can do without the catalogue. Details are in notebook 23.

**Comment by chengsoonong** [comment]
To be very geeky, you can tikz it:
http://www.texample.net/tikz/examples/venn-diagram/

Some random thoughts about Venn Diagrams:
http://www.combinatorics.org/files/Surveys/ds5/VennEJC.html

**Comment by MatthewJA** [comment]
I'm happy to close this, now, since the ideal data set is very small (though it might be less small for FIRST&ndash;RGZ).
