### ISSUE TITLE
Filter stars from SWIRE results

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#52]
Stars are bright in the IR bands &mdash; orders of magnitude more so than galaxies. This is probably causing them to be preferenced for classification, and is probably making the flux features less useful due to the scale difference.

**Comment by MatthewJA** [comment]
#36

**Comment by chengsoonong** [comment]
From email:

Regarding screening stars from the SWIRE results (so we only look at galaxies), the SWIRE catalogue seems to contain a stellarity index for each band. I assume I need to ignore objects with sufficiently high stellarity. Do you know what band/s should I be checking (out of 2.4 μm, 3.6 μm, 4.5 μm, 5.8 μm, and 8.0 μm) and what level of stellarity index counts as "sufficiently high"?

**Comment by jbanfield** [comment]
Have a read through section 8.4.10: galaxy-star separation.
http://irsa.ipac.caltech.edu/data/SPITZER/SWIRE/docs/delivery_doc_r2_v2.pdf
Note - this is only for the SWIRE data, WISE will have a different flag.

**Comment by MatthewJA** [comment]
Thanks Julie! I believe that stellarity index is a continuous variable from 0 to 1 in the infrared bands (it's only a flag in optical). As such, I probably need to have a cutoff value. A quick plot of some starry images doesn't show a clear cutoff like I had expected. I'll see if I can find the distribution of these values across the data set.

P.S., I've added an "astro" label on astro-related issues. This should hopefully make it clearer what is astro-related and what is comp-related, so using GitHub will be easier.

**Comment by jbanfield** [comment]
Is there a way to change my email settings to get only the astro issues?

**Comment by jbanfield** [comment]
1 would be the most point-like.  Maybe start with 0.75 and see how/if this helps.

**Comment by MatthewJA** [comment]
> Is there a way to change my email settings to get only the astro issues?

Not to my knowledge. I could "assign" you to relevant issues, which would trip a different kind of email, and you could filter out all the others in your email client, maybe?

> 1 would be the most point-like. Maybe start with 0.75 and see how/if this helps.

Okay! I'll try this.

**Comment by MatthewJA** [comment]
Bizarrely, dropping objects with stellarity > 0.9 and flux > 1000 (or any combination thereof) drops the accuracy _massively_ &mdash; 60% down to 30%.

**Comment by chengsoonong** [comment]
What is the performance of the classifier on objects with stellarity > 0.9 and/or flux > 1000?

**Comment by MatthewJA** [comment]
~36%, c.f. ~63% without the cap.

**Comment by MatthewJA** [comment]
Not sure! I'll take a look.

**Comment by MatthewJA** [comment]
20% on just the stellarity cutoff. 3% on just the flux cutoff.

The implication is that a lot of objects chosen by volunteers have very high stellarity; I should make a histogram of stellarities of classified objects.

**Comment by chengsoonong** [comment]
Also make a table of the number of examples in each setting. You may have a "too small training set" problem.

**Comment by MatthewJA** [comment]
#69

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/15730539/e7c44c78-28b0-11e6-96da-8295b414080b.png)

By the way, here's a histogram of stellarities of consensus objects. They pretty much match the distribution of stellarities, as I'd expect if they were chosen at random.

**Comment by MatthewJA** [comment]
![image](https://cloud.githubusercontent.com/assets/2681312/15918677/a34c0828-2e4c-11e6-9d7e-20b0bb1f8350.png)

Previous comment was somewhat in accurate. The distribution is close to the original, but there's a clear preference for less-stellar objects. Now to find out what the classifier thinks...

**Comment by jbanfield** [comment]
can you explain what the different colour mean in the above plot?

**Comment by MatthewJA** [comment]
Sure. Blue is the distribution of stellarity indices of SWIRE objects, and red is the distribution of stellarity indices of SWIRE objects nearest to Radio Galaxy Zoo consensus locations.

**Comment by MatthewJA** [comment]
WISE doesn't seem to have an analogue of the stellarity index, so we might be out of luck for WISE.

**Comment by MatthewJA** [comment]
Since we're using WISE now, this seems impossible.
