### ISSUE TITLE
Is there a table relating ATLAS IDs (in the catalogue) to survey IDs (in Radio Talk and the image filenames)?

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#63]
The filenames of CDFS and ELAIS images are the same IDs used on the Radio Talk website and in `radio_subjects.json`, but they are not the same IDs used in the ATLAS catalogue. To match ATLAS names to these images, I need to convert between the two IDs.

Is there a standard way of doing this (such as a conversion table), or should I just look for the ATLAS catalogue object nearest each radio component?

**Comment by jbanfield** [comment]
Yes they are not the same.  The only way to do this is to search the ATLAS catalogue for the closest radio source.

**Comment by MatthewJA** [comment]
Okay, thanks!

**Comment by MatthewJA** [comment]
I've added a threshold for how close something can be before it is not counted as a match. At the moment this is 0.0016 degrees; this results in 212(!) components not being matched. I'm not sure what the maximum reasonable threshold would be &mdash; for SWIRE we used 0.00083, but SWIRE is higher resolution. Does this threshold sound reasonable? Would it be reasonable to raise it?

0.02 degrees skips 78 components.

**Comment by jbanfield** [comment]
This needs to be matched with the radio positions not the SWIRE positions

**Comment by MatthewJA** [comment]
Yes, I mean with the radio positions (from the ATLAS catalogue).

**Comment by jbanfield** [comment]
I've matched them.  Will send you the translation through email.

**Comment by MatthewJA** [comment]
Received, thanks! The difference in position is larger than I had expected, which explains why I was skipping so many components.

**Comment by chengsoonong** [comment]
Please add the matching to crowdastro-data Matthew.

**Comment by MatthewJA** [comment]
Sure!

**Comment by jbanfield** [comment]
the separation is in arcsec not degrees so it is not as big as you think

**Comment by MatthewJA** [comment]
Some components seem to be missing, e.g. CI0005C1. I'm skipping missing components for now but please let me know if this is an error.
