### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#65]
The internet seems to think that because nose is no longer developed, we should consider something else.

pytest seems popular. 
http://pytest.org/latest/

Open to discussion.

**Comment by MatthewJA** [comment]
pytest looks nice. I'm using unittest at the moment (since it's built-in) but perhaps that would be a better option.

**Comment by MatthewJA** [comment]
Messing with pytest a bit, and I'm not feeling it. It seems somewhat over-engineered. I'm going to use unittest for now unless you have objections.

(Closing this issue under the assumption it's about pytest and not testing in general &mdash; currently writing unit tests for import_data)
