### ISSUE TITLE
command line for gator_cache?

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#67]
Or is this deprecated?

**Comment by MatthewJA** [comment]
What do you mean? Do you mean setting the Gator cache to have a default argument?

**Comment by chengsoonong** [comment]
I mean have a command line argument to create the file gator_cache.sqlite

Which incidentally should be called gator_cache.db to be consistent with processed.db

**Comment by MatthewJA** [comment]
It's created automatically if it doesn't exist. That said, I want to replace it with the SWIRE catalogue directly (#58) and am currently in the process of doing so.

**Comment by chengsoonong** [comment]
I meant that to generate training data, I seem to need gator_cache.
python3 -m crowdastro training_data processed.db consensuses gator_cache training.h5 --atlas

But perhaps that file is created directly.

Let's close this issue, since we will avoid gator_cache by using the SWIRE catalog directly.
