### ISSUE TITLE
Make a table of how much data is thrown out by various filters

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#69]

**Comment by MatthewJA** [comment]
| SWIRE data set | count | percentage |
| --- | --- | --- |
| all | 30853 | 100% |
| training | 25933 | 84% |
| training < 0.9 stellarity | 19671 | 64% |
| training < 1000 µJy flux | 25062 | 81% |
| testing | 4920 | 16% |
| testing < 0.9 stellarity | 3684 | 12% |
| testing < 1000 µJy flux | 4763 | 15% |

**Comment by chengsoonong** [comment]
I suggest that you do the splitting into training, validation and test AFTER you do the filtering. That way, you don't need to report percentages for training and testing above.

**Comment by MatthewJA** [comment]
Merge into #105.
