### ISSUE TITLE
Use FITS format

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#7]
Julie to provide FITS files (replacing current jpg)

**Comment by jbanfield** [comment]
Sent email in regards to the links for the files.  Too large for me to upload to the gitlab data storage.  I will add more information to the wiki section in regards to this 2000 radio subject sample.

**Comment by jbanfield** [comment]
Description on the wiki section.

**Comment by MatthewJA** [comment]
Resolved in #12.

**Comment by chengsoonong** [comment]
In general, please try to make it easy for me to check by writing a clear comment about which notebook I need to look at. README should also have bullet points about which notebook to run for any particular function.
