### ISSUE TITLE
Is there a single ATLAS-CDFS image?

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#70]
Is there a single FITS image associated with the radio CDFS field? I've found one from 2007 but it seems much lower quality than the images Julie has provided pre-split into subjects. If possible, I'd prefer to use the full image rather than the pre-split images.

**Comment by MatthewJA** [comment]
@jbanfield

**Comment by jbanfield** [comment]
yes there is one.  I'll email the link

**Comment by MatthewJA** [comment]
Thanks Julie! This should hopefully simplify the code a lot.

**Comment by jbanfield** [comment]
Note that this won't be the case for FIRST.

**Comment by MatthewJA** [comment]
What format are the FIRST images in? Are they only available as individual subjects like the original format I received ATLAS in, or are they a small number of separate images?

**Comment by jbanfield** [comment]
The FIRST images are FITS.  You can grab any size image from here: [http://third.ucllnl.org/cgi-bin/firstcutout](url)

However, the images are put into RGZ at 5arcmin x 5arcmin.

**Comment by MatthewJA** [comment]
Okay, thanks! I think this will be fine.
