### ISSUE TITLE
How many objects have been classified by Radio Galaxy Zoo so far?

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#71]
A number is given in the 2015 paper but I understand this is somewhat out of date. My data has 94407 complete classifications, but I think that's also somewhat out of date. Is there a more up-to-date number? I'd like to put it in my upcoming report.

**Comment by MatthewJA** [comment]
@jbanfield

**Comment by jbanfield** [comment]
1,689,511 classifications as of today.

**Comment by MatthewJA** [comment]
Thanks Julie! Additionally, how many subjects are marked complete?

**Comment by jbanfield** [comment]
Today, total classification 1,967,260.

104,596 sources are complete out of the total 177,281

**Comment by MatthewJA** [comment]
Great, thanks!
