### ISSUE TITLE
Put crowdastro on PyPI

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#79]

**Comment by chengsoonong** [comment]
Version 0.1 after Julie manages to run code.

**Comment by MatthewJA** [comment]
Julie's progress is here: #116

Since the code isn't working on the RSAA server yet, I'm moving this into milestone D.

**Comment by chengsoonong** [comment]
http://stsdas.stsci.edu/download/packaging-overview.pdf

**Comment by chengsoonong** [comment]
https://packaging.python.org/distributing/

**Comment by MatthewJA** [comment]
> Since the code isn't working on the RSAA server yet, I'm moving this into milestone D.

Same, but milestone E.

**Comment by chengsoonong** [comment]
Bumping this to the top of the priority queue. We should make a release this week, and when it works on RSAA server, update the release if there are any bug fixes.

**Comment by MatthewJA** [comment]
Working on it!

**Comment by MatthewJA** [comment]
Currently working on getting an entry point working, so you'll be able to go `crowdastro consensuses` (for example) and it will work. The code is a little odd, but it seems to work pretty well and has minimal duplication.

**Comment by MatthewJA** [comment]
[Uploaded to PyPi!](https://pypi.python.org/pypi/crowdastro/)

Pending some fixes...
