### ISSUE TITLE
Analyse data for interesting astrophysics things

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#80]
#56 #52 #35

Also check astrophysical properties of
- uncertain objects
- certain but wrong objects
- influential data points (e.g. removing these data points changes classification accuracy by a large amount)

and anything @jbanfield thinks might be interesting.

**Comment by jbanfield** [comment]
Agree, best to brainstorm over a coffee on this one.

**Comment by MatthewJA** [comment]
[Here are some "certain" and "uncertain" objects.](https://github.com/chengsoonong/crowdastro/blob/master/notebooks/41_classification_experiments.ipynb)

**Comment by MatthewJA** [comment]
Let's define "interesting" as "uncertain" objects, as determined by classifier committee disagreement. #104
