### ISSUE TITLE
Formalise and write up experimental design

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#81]

**Comment by chengsoonong** [comment]
Just recalled that your mid-term presentation is next Friday, and it would be good to be able to show one plot about active learning at the end of the presentation.

**Comment by MatthewJA** [comment]
Shall try and get it done before then. I've got a basic uncertainty sampler already but it acts really strangely...

**Comment by MatthewJA** [comment]
Merged into #105.
