### ISSUE TITLE
Write up comments on Banfield et al. (2015)

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#83]

**Comment by jbanfield** [comment]
Let me know if you require anything from me for this.

**Comment by chengsoonong** [comment]
@MatthewJA Write one page in thesis discussing:
- redundancy level
- when does KDE not work

**Comment by MatthewJA** [comment]
A note: I haven't seen much literature on active learning with noisy oracles and repeated labelling which models the relabelling rate as a function of the features. Settles' Active Learning in Practice (2011) puts this as an open question and it's covered as part of Mozafari et al. (2012) (though I don't really understand their approach). The model of oracle noise developed by Yan et al. (2010) is input-dependent, but I believe that neither this paper nor their later 2011 paper look at repeated labelling.

**Comment by MatthewJA** [comment]
This is probably interesting to both my honours project and the Radio Galaxy Zoo in general, since some radio objects are intrinsically harder to label than others. Maybe these objects are astrophysically interesting? At any rate, they need higher redundancy than others.

**Comment by chengsoonong** [comment]
This is a good observation @MatthewJA.

Active learning with repeated noisy labels is an interesting and open problem, and would be a good topic to work on for your honours. You will of course need to understand Mozafari. One useful bit of research would be to implement both papers, and compare the two methods empirically on your data. Then if you can come up with any other ideas, it would be a nice high point to your work.

Just for your overall education, there are other fields of literature which deal with repeated noisy labels. These are called "bandits", "experimental design", "partial monitoring". At this point, I think it is too much for you to try to understand those areas too, so it is ok to just look at active learning, as (I think) it is the most suitable for your project.
