### ISSUE TITLE
Implement active learning algorithm into Radio Galaxy Zoo website

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/crowdastro#85]
I don't actually know if this is _possible_ within the time frame of this project, but I'll at very least have a look and try it.

**Comment by MatthewJA** [comment]
This depends somewhat on how the website is implemented. It looks like it's written in CoffeeScript, which happens to be one of the languages I actually know &mdash; so that's nice. It looks like a well-written web app and the code is pretty nice with standard MVC patterns. It's using the `zooniverse` library for subject selection. One way to implement might be to override this &mdash; it seems you can also query by Zooniverse ID, so a simple way to implement within the existing Python framework would be to have a simple server serving Zooniverse IDs. Or I can implement everything in CoffeeScript. That's fine, too.

**Comment by jbanfield** [comment]
When you mean active learning, does this correspond to the retirement rate of radio subjects?

**Comment by MatthewJA** [comment]
Active learning involves choosing which unlabelled subject to present to volunteers based on prior classifications. The idea is that you present subjects that give you the most information gain, so the machine learning classifier can learn faster. Part of this would likely be modelling the retirement rate, so more certain subjects are shown less often.
