### ISSUE TITLE
Rotation invariance

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#94]
Generate training examples for the CNN that are rotations of the original image. This forces the learned features to be invariant to rotation. If possible to train within a sensible amount of time, then 8 or 16 or 32 rotations.

Can also test the prediction accuracy on rotated images.

**Comment by MatthewJA** [comment]
Probably not going to have time to do this and it seems less important than scale invariance.

(noting that [I think] ATLAS is not actually rotationally invariant)
