### ISSUE TITLE
 Difference between ATLAS-SWIRE and ATLAS-WISE

### ISSUE THREAD

**Issue by jbanfield** [chengsoonong/crowdastro#97]
All future radio data is going to be matched to WISE and not SWIRE.  WISE is lower resolution and higher noise.  The radio data will be similar to the ATLAS radio data.  Can we run the classifier on WISE images to see if we get the same thing as running on SWIRE images with ATLAS radio data?

**Comment by MatthewJA** [comment]
Tagging #73 for reference.

Sure, we can do that. The only infrared inputs to the classifier (so far) are the positions and fluxes of each infrared object, all of which are taken from the SWIRE CDFS Fall '05 catalogue. I need a similar catalogue for WISE &mdash; do you know if this would be the AllWISE Source Catalog, the All-Sky Source Catalog, or neither?

**Comment by jbanfield** [comment]
WISE is a very large catalogue (all-sky). We will need to just grab the sources within our area of interest for the moment.  Unless you have the bandwidth and storage for the catalogue on you machine.

All-sky catalogue is here: [http://wise2.ipac.caltech.edu/docs/release/allsky/](http://wise2.ipac.caltech.edu/docs/release/allsky/)

**Comment by MatthewJA** [comment]
Grabbed the CDFS field from AllWISE last night and ran it through. Volunteers tended to agree with WISE 8 percentage points more than they agreed with SWIRE. Logistic regression accuracy dropped to ~65% Norris et al. agreement, and random forests dropped to ~75% Norris et al. agreement. Random forest accuracy jumped to 94% against the RGZ classifications.

Note that when importing WISE, the training set was regenerated and thus contains different examples to the training set for SWIRE, so these numbers may have varied a little just from that.

**Comment by MatthewJA** [comment]
I had a bug in both the SWIRE and WISE tests! For WISE (matching Norris et al. classifications to the nearest WISE object), 86% agreement with RGZ volunteers, 82% agreement with Norris et al., 92% agreement with either. Haven't rerun the SWIRE tests since I'll have to reimport SWIRE and that takes a while.
