### ISSUE TITLE
Interesting related astronomy papers

### ISSUE THREAD

**Issue by jbanfield** [chengsoonong/crowdastro#98]
**Unsupervised learning**
Hocking, Geach, Davey & Sun (2015) [http://arxiv.org/abs/1507.01589](http://arxiv.org/abs/1507.01589)

**Supervised learning**
Dieleman, Willett & Dambre (2015) [http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:1503.07077](http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:1503.07077)

**Comment by jbanfield** [comment]
and references within

**Comment by jbanfield** [comment]
ATLAS-SWIRE cross-ids without RGZ data.  It looks like they assume that all the radio components are in a line. 

Fan et al. (2015) [http://adsabs.harvard.edu/abs/2015MNRAS.451.1299F](http://adsabs.harvard.edu/abs/2015MNRAS.451.1299F)

**Comment by MatthewJA** [comment]
An interesting point is that previous ML applications in astronomy seem to use much closer objects than we are &mdash; our radio objects are much further away and less resolved. For this reason, I'm curious as to what the other RGZ student project is doing.

I wonder if Fan et al. have a catalogue? That would make a very interesting comparison.

**Comment by jbanfield** [comment]
I will email Fan to see what is available.

Added you to the wiki page so you can have access to the other projects.

**Comment by MatthewJA** [comment]
Thanks!

I might make an issue containing all the required reading, since there's a few different issues about that now.

**Comment by MatthewJA** [comment]
Looks like the other project might find some ways to extract useful radio features. With that in mind, I'm going to avoid doing much of that topic &mdash; I'm quite happy with the CNN as it stands, bar issue #99.

**Comment by MatthewJA** [comment]
Merged into #101.
